vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
       avatars:
           uri_prefix: /media/avatars
           upload_destination: '%kernel.project_dir%/public/media/avatars'
           namer: vich_uploader.namer_origname

        #    delete_on_update: true
        #    delete_on_remove: true

       trick_images:
           uri_prefix: /media/images
           upload_destination: '%kernel.project_dir%/public/media/images'
           namer: vich_uploader.namer_origname

           delete_on_update: true
           delete_on_remove: true

